/*
 * stm32_synth_program.h
 *
 *  Created on: Oct 10, 2024
 *      Author: k-omura
 */

#ifndef STM32_SYNTH_COMPONENTS_STM32_SYNTH_PROGRAM_H_
#define STM32_SYNTH_COMPONENTS_STM32_SYNTH_PROGRAM_H_

#include "stm32_synth.h"

typedef enum
{
	// Piano Timbres:
	STM32SYNTH_PROGRAM_ACOUSTIC_GRAND_PIANO = 0, // Acoustic Grand Piano
	STM32SYNTH_PROGRAM_BRIGHT_ACOUSTIC_PIANO,	 // Bright Acoustic Piano
	STM32SYNTH_PROGRAM_ELECTRIC_GRAND_PIANO,	 // Electric Grand Piano
	STM32SYNTH_PROGRAM_HONKYTONK_PIANO,			 // Honky-tonk Piano
	STM32SYNTH_PROGRAM_RHODES_PIANO,			 // Rhodes Piano
	STM32SYNTH_PROGRAM_CHORUSED_PIANO,			 // Chorused Piano
	STM32SYNTH_PROGRAM_HARPSICHORD,				 // Harpsichord
	STM32SYNTH_PROGRAM_CLAVINET,				 // Clavinet

	// Chromatic Percussion:
	STM32SYNTH_PROGRAM_CELESTA,		  // Celesta
	STM32SYNTH_PROGRAM_GLOCKENSPIEL,  // Glockenspiel
	STM32SYNTH_PROGRAM_MUSIC_BOX,	  // Music Box
	STM32SYNTH_PROGRAM_VIBRAPHONE,	  // Vibraphone
	STM32SYNTH_PROGRAM_MARIMBA,		  // Marimba
	STM32SYNTH_PROGRAM_XYLOPHONE,	  // Xylophone
	STM32SYNTH_PROGRAM_TUBULAR_BELLS, // Tubular Bells
	STM32SYNTH_PROGRAM_DULCIMER,	  // Dulcimer

	// Organ Timbres:
	STM32SYNTH_PROGRAM_HAMMOND_ORGAN,	 // Hammond Organ
	STM32SYNTH_PROGRAM_PERCUSSIVE_ORGAN, // Percussive Organ
	STM32SYNTH_PROGRAM_ROCK_ORGAN,		 // Rock Organ
	STM32SYNTH_PROGRAM_CHURCH_ORGAN,	 // Church Organ
	STM32SYNTH_PROGRAM_REED_ORGAN,		 // Reed Organ
	STM32SYNTH_PROGRAM_ACCORDION,		 // Accordion
	STM32SYNTH_PROGRAM_HARMONICA,		 // Harmonica
	STM32SYNTH_PROGRAM_TANGO_ACCORDION,	 // Tango Accordion

	// Guitar Timbres:
	STM32SYNTH_PROGRAM_ACOUSTIC_NYLON_GUITAR, // Acoustic Nylon Guitar
	STM32SYNTH_PROGRAM_ACOUSTIC_STEEL_GUITAR, // Acoustic Steel Guitar
	STM32SYNTH_PROGRAM_ELECTRIC_JAZZ_GUITAR,  // Electric Jazz Guitar
	STM32SYNTH_PROGRAM_ELECTRIC_CLEAN_GUITAR, // Electric Clean Guitar
	STM32SYNTH_PROGRAM_ELECTRIC_MUTED_GUITAR, // Electric Muted Guitar
	STM32SYNTH_PROGRAM_OVERDRIVEN_GUITAR,	  // Overdriven Guitar
	STM32SYNTH_PROGRAM_DISTORTION_GUITAR,	  // Distortion Guitar
	STM32SYNTH_PROGRAM_GUITAR_HARMONICS,	  // Guitar Harmonics

	// Bass Timbres:
	STM32SYNTH_PROGRAM_ACOUSTIC_BASS,		   // Acoustic Bass
	STM32SYNTH_PROGRAM_FINGERED_ELECTRIC_BASS, // Fingered Electric Bass
	STM32SYNTH_PROGRAM_PLUCKED_ELECTRIC_BASS,  // Plucked Electric Bass
	STM32SYNTH_PROGRAM_FRETLESS_BASS,		   // Fretless Bass
	STM32SYNTH_PROGRAM_SLAP_BASS_1,			   // Slap Bass 1
	STM32SYNTH_PROGRAM_SLAP_BASS_2,			   // Slap Bass 2
	STM32SYNTH_PROGRAM_SYNTH_BASS_1,		   // Synth Bass 1
	STM32SYNTH_PROGRAM_SYNTH_BASS_2,		   // Synth Bass 2

	// String Timbres:
	STM32SYNTH_PROGRAM_VIOLIN,			  // Violin
	STM32SYNTH_PROGRAM_VIOLA,			  // Viola
	STM32SYNTH_PROGRAM_CELLO,			  // Cello
	STM32SYNTH_PROGRAM_CONTRABASS,		  // Contrabass
	STM32SYNTH_PROGRAM_TREMOLO_STRINGS,	  // Tremolo Strings
	STM32SYNTH_PROGRAM_PIZZICATO_STRINGS, // Pizzicato Strings
	STM32SYNTH_PROGRAM_ORCHESTRAL_HARP,	  // Orchestral Harp
	STM32SYNTH_PROGRAM_TIMPANI,			  // Timpani

	// Ensemble Timbres:
	STM32SYNTH_PROGRAM_STRING_ENSEMBLE_1, // String Ensemble 1
	STM32SYNTH_PROGRAM_STRING_ENSEMBLE_2, // String Ensemble 2
	STM32SYNTH_PROGRAM_SYNTH_STRINGS_1,	  // Synth Strings 1
	STM32SYNTH_PROGRAM_SYNTH_STRINGS_2,	  // Synth Strings 2
	STM32SYNTH_PROGRAM_CHOIR_AAH,		  // Choir "Aah"
	STM32SYNTH_PROGRAM_CHOIR_OOH,		  // Choir "Ooh"
	STM32SYNTH_PROGRAM_SYNTH_VOICE,		  // Synth Voice
	STM32SYNTH_PROGRAM_ORCHESTRAL_HIT,	  // Orchestral Hit

	// Brass Timbres:
	STM32SYNTH_PROGRAM_TRUMPET,		  // Trumpet
	STM32SYNTH_PROGRAM_TROMBONE,	  // Trombone
	STM32SYNTH_PROGRAM_TUBA,		  // Tuba
	STM32SYNTH_PROGRAM_MUTED_TRUMPET, // Muted Trumpet
	STM32SYNTH_PROGRAM_FRENCH_HORN,	  // French Horn
	STM32SYNTH_PROGRAM_BRASS_SECTION, // Brass Section
	STM32SYNTH_PROGRAM_SYNTH_BRASS_1, // Synth Brass 1
	STM32SYNTH_PROGRAM_SYNTH_BRASS_2, // Synth Brass 2

	// Reed Timbres:
	STM32SYNTH_PROGRAM_SOPRANO_SAX,	 // Soprano Sax
	STM32SYNTH_PROGRAM_ALTO_SAX,	 // Alto Sax
	STM32SYNTH_PROGRAM_TENOR_SAX,	 // Tenor Sax
	STM32SYNTH_PROGRAM_BARITONE_SAX, // Baritone Sax
	STM32SYNTH_PROGRAM_OBOE,		 // Oboe
	STM32SYNTH_PROGRAM_ENGLISH_HORN, // English Horn
	STM32SYNTH_PROGRAM_BASSOON,		 // Bassoon
	STM32SYNTH_PROGRAM_CLARINET,	 // Clarinet

	// Pipe Timbres:
	STM32SYNTH_PROGRAM_PICCOLO,		// Piccolo
	STM32SYNTH_PROGRAM_FLUTE,		// Flute
	STM32SYNTH_PROGRAM_RECORDER,	// Recorder
	STM32SYNTH_PROGRAM_PAN_FLUTE,	// Pan Flute
	STM32SYNTH_PROGRAM_BOTTLE_BLOW, // Bottle Blow
	STM32SYNTH_PROGRAM_SHAKUHACHI,	// Shakuhachi
	STM32SYNTH_PROGRAM_WHISTLE,		// Whistle
	STM32SYNTH_PROGRAM_OCARINA,		// Ocarina

	// Synth Lead:
	STM32SYNTH_PROGRAM_SQUARE_WAVE_LEAD,   // Square Wave Lead
	STM32SYNTH_PROGRAM_SAWTOOTH_WAVE_LEAD, // Sawtooth Wave Lead
	STM32SYNTH_PROGRAM_CALLIOPE_LEAD,	   // Calliope Lead
	STM32SYNTH_PROGRAM_CHIFF_LEAD,		   // Chiff Lead
	STM32SYNTH_PROGRAM_CHARANG_LEAD,	   // Charang Lead
	STM32SYNTH_PROGRAM_VOICE_LEAD,		   // Voice Lead
	STM32SYNTH_PROGRAM_FIFTHS_LEAD,		   // Fifths Lead
	STM32SYNTH_PROGRAM_BASS_LEAD,		   // Bass Lead

	// Synth Pad:
	STM32SYNTH_PROGRAM_NEW_AGE_PAD,	  // New Age Pad
	STM32SYNTH_PROGRAM_WARM_PAD,	  // Warm Pad
	STM32SYNTH_PROGRAM_POLYSYNTH_PAD, // Polysynth Pad
	STM32SYNTH_PROGRAM_CHOIR_PAD,	  // Choir Pad
	STM32SYNTH_PROGRAM_BOWED_PAD,	  // Bowed Pad
	STM32SYNTH_PROGRAM_METALLIC_PAD,  // Metallic Pad
	STM32SYNTH_PROGRAM_HALO_PAD,	  // Halo Pad
	STM32SYNTH_PROGRAM_SWEEP_PAD,	  // Sweep Pad

	// Synth Effects:
	STM32SYNTH_PROGRAM_RAIN_EFFECT,		  // Rain Effect
	STM32SYNTH_PROGRAM_SOUNDTRACK_EFFECT, // Soundtrack Effect
	STM32SYNTH_PROGRAM_CRYSTAL_EFFECT,	  // Crystal Effect
	STM32SYNTH_PROGRAM_ATMOSPHERE_EFFECT, // Atmosphere Effect
	STM32SYNTH_PROGRAM_BRIGHTNESS_EFFECT, // Brightness Effect
	STM32SYNTH_PROGRAM_GOBLINS_EFFECT,	  // Goblins Effect
	STM32SYNTH_PROGRAM_ECHOES_EFFECT,	  // Echoes Effect
	STM32SYNTH_PROGRAM_SCI_FI_EFFECT,	  // Sci-Fi Effect

	// Ethnic Timbres:
	STM32SYNTH_PROGRAM_SITAR,	 // Sitar
	STM32SYNTH_PROGRAM_BANJO,	 // Banjo
	STM32SYNTH_PROGRAM_SHAMISEN, // Shamisen
	STM32SYNTH_PROGRAM_KOTO,	 // Koto
	STM32SYNTH_PROGRAM_KALIMBA,	 // Kalimba
	STM32SYNTH_PROGRAM_BAGPIPE,	 // Bagpipe
	STM32SYNTH_PROGRAM_FIDDLE,	 // Fiddle
	STM32SYNTH_PROGRAM_SHANAI,	 // Shanai

	// Sound Effects:
	STM32SYNTH_PROGRAM_TINKLE_BELL,	   // Tinkle Bell
	STM32SYNTH_PROGRAM_AGOGO,		   // Agogo
	STM32SYNTH_PROGRAM_STEEL_DRUMS,	   // Steel Drums
	STM32SYNTH_PROGRAM_WOODBLOCK,	   // Woodblock
	STM32SYNTH_PROGRAM_TAIKO_DRUM,	   // Taiko Drum
	STM32SYNTH_PROGRAM_MELODIC_TOM,	   // Melodic Tom
	STM32SYNTH_PROGRAM_SYNTH_DRUM,	   // Synth Drum
	STM32SYNTH_PROGRAM_REVERSE_CYMBAL, // Reverse Cymbal

	// Sound Effects:
	STM32SYNTH_PROGRAM_GUITAR_FRET_NOISE, // Guitar Fret Noise
	STM32SYNTH_PROGRAM_BREATH_NOISE,	  // Breath Noise
	STM32SYNTH_PROGRAM_SEASHORE,		  // Seashore
	STM32SYNTH_PROGRAM_BIRD_TWEET,		  // Bird Tweet
	STM32SYNTH_PROGRAM_TELEPHONE_RING,	  // Telephone Ring
	STM32SYNTH_PROGRAM_HELICOPTER,		  // Helicopter
	STM32SYNTH_PROGRAM_APPLAUSE,		  // Applause
	STM32SYNTH_PROGRAM_GUN_SHOT,		  // Gun Shot
} stm32synth_program_list_t;

stm32synth_res_t stm32synth_program_clear(stm32synth_config_t *_config, uint8_t _ch);
stm32synth_res_t stm32synth_program_set(stm32synth_config_t *_config, uint8_t _ch, stm32synth_program_list_t _program);

#endif /* STM32_SYNTH_COMPONENTS_STM32_SYNTH_PROGRAM_H_ */
