from enum import Enum, IntEnum
    
class MidiMsg(IntEnum):
    NOTEOFF = 0x80,
    NOTEON = 0x90,
    AFTERTOUCH = 0xA0,
    CONTROLCHANGE = 0xB0,
    PROGRAMCHANGE = 0xC0,
    CHANNELAFTERTOUCH = 0xD0,
    PITCHBEND = 0xE0

class MidiCC(IntEnum):
    BANKSLECT = 0,               # Allows user to switch bank for patch selection. Program change used with Bank Select. MIDI can access 16,384 patches per MIDI channel.
    MODWHELL = 1,			     # Generally this CC controls a vibrato effect (pitch, loudness, brighness). What is modulated is based on the patch.
    BREATHCONT = 2,              # Oftentimes associated with aftertouch messages. It was originally intended for use with a breath MIDI controller in which blowing harder produced higher MIDI control values. It can be used for modulation as well.
    FOOTCONT = 4,                # Often used with aftertouch messages. It can send a continuous stream of values based on how the pedal is used.
    PORTAMENTOTIME = 5,          # Controls portamento rate to slide between 2 notes played subsequently.
    DATAENTRY = 6,               # Controls Value for NRPN or RPN parameters.
    VOLUME = 7,                  # Controls the volume of the channel.
    BALANCE = 8,                 # Controls the left and right balance, generally for stereo patches. A value of 64 equals the center.
    PAN = 10,                    # Controls the left and right balance, generally for mono patches. A value of 64 equals the center.
    EXPRESSION = 1,              # Expression is a percentage of volume (CC7).
    EFFECTCONT1 = 2,             # Usually used to control a parameter of an effect within the synth or workstation.
    EFFECTCONT2 = 3,             # Usually used to control a parameter of an effect within the synth or workstation.
    GENERAL16 = 16,              #
    GENERAL17 = 17,              #
    GENERAL18 = 18,              #
    GENERAL19 = 19,              #
    USER_ATTACKLEVEL = 20,       #
    USER_WAVE1SINEAMP = 21,		 #
    USER_WAVE1SQUAMP = 22,		 #
    USER_WAVE1SQUDUTY = 23,		 #
    USER_WAVE1TRIAMP = 24,		 #
    USER_WAVE1TRIPEAK = 25,		 #
    USER_WAVE1PITCH = 26,		 #
    USER_WAVE1OCTAVE = 27,		 #
    USER_WAVE2SINEAMP = 28,		 #
    USER_WAVE2SQUAMP = 29,		 #
    USER_WAVE2SQUDUTY = 30,		 #
    USER_WAVE2TRIAMP = 31,		 #
    USER_WAVE2TRIPEAK = 32,	     #
    USER_WAVE2PITCH = 33,        #
    USER_WAVE2OCTAVE = 34,	     #
    USER_DISTORTION_LEVEL = 35,  #
    USER_PITCHBYNOTE = 36,       #
    USER_FILTERTYPE = 37,        #
    USER_CH0MIRRORCH = 38,       #
    USER_TRE_TYPE = 39,          #
    USER_TRE_PEAK = 40,          #
    USER_TRE_FREQ = 41,          #
    USER_VIB_TYPE = 42,          #
    USER_VIB_PEAK = 43,          #
    USER_VIB_AMP = 44,           #
    USER_VIB_FREQ = 45,          #
    USER_WOW_TYPE = 46,          #
    USER_WOW_PEAK = 47,          #
    USER_WOW_AMP = 48,           #
    USER_WOW_FREQ = 49,          #
    USER_ENV_VOL_DIFF = 50,		 #
    USER_ENV_VOL_TIME = 51,		 #
    USER_ENV_FREQ_DIFF = 52,     #
    USER_ENV_FREQ_TIME = 53,	 #
    USER_ENV_WOW_DIFF = 54,		 #
    USER_ENV_WOW_TIME = 55,		 #
    USER_DRUM_NN = 56,			 #
    USER_DRUM_TYPE = 57,	     #
    USER_DRUM_LPF_FCNN = 58,   	 #
    USER_DRUM_HPF_FCNN = 59,	 #
    USER_DRUM_LPF_Q = 60,		 #
    USER_DRUM_HPF_Q = 61,		 #
    DAMPERPEDAL = 64,            # ≤63 off, ≥64 on. On/off switch that controls sustain pedal. Nearly every synth will react to CC 64. (See also Sostenuto CC 66)
    PORTAMENTO = 65,             # ≤63 off, ≥64 on. On/off switch
    SOSTENTOPEDAL = 66,          # ≤63 off, ≥64 on. On/off switch – Like the Sustain controller (CC 64), However, it only holds notes that were “On” when the pedal was pressed. People use it to “hold” chords” and play melodies over the held chord.
    SOFTPEDAL = 67,              # ≤63 off, ≥64 on.	On/off switch – Lowers the volume of notes played.
    LEGATOFOOTSWITCH = 68,       # ≤63 off, ≥64 on. On/off switch – Turns Legato effect between 2 subsequent notes on or off.
    HOLD2 = 69,                  # ≤63 off, ≥64 on	Another way to “hold notes” (see MIDI CC 64 and MIDI CC 66). However notes fade out according to their release parameter rather than when the pedal is released.
    SOUNDCONT1 = 70,             # Usually controls the way a sound is produced. Default =  Sound Variation.
    SOUNDCONT2 = 71,             # Allows shaping the Voltage Controlled Filter (VCF). Default =  Resonance also (Timbre or Harmonics)
    USER_FILTERQFACTOR = 71,     # Resonance of the filter(q factor)
    SOUNDCONT3 = 72,             # Controls release time of the Voltage controlled Amplifier (VCA). Default =  Release Time.
    USER_RELEASETIME = 72,       # Release Time
    SOUNDCONT4 = 73,             # Controls the “Attack’ of a sound. The attack is the amount of time it takes for the sound to reach maximum amplitude.
    USER_ATTACKTIME = 73,        # Controls the “Attack’ of a sound. The attack is the amount of time it takes for the sound to reach maximum amplitude.
    SOUNDCONT5 = 74,             # Controls VCFs cutoff frequency of the filter.
    USER_FILTERCUTOFF = 74,      # cutoff frequency of the filter
    GENERAL75 = 75,              # Generic – Some manufacturers may use to further shave their sounds.
    GENERAL76 = 76,              # Generic – Some manufacturers may use to further shave their sounds.
    GENERAL77 = 77,              # Generic – Some manufacturers may use to further shave their sounds.
    GENERAL78 = 78,              # Generic – Some manufacturers may use to further shave their sounds.
    GENERAL79 = 79,              # Generic – Some manufacturers may use to further shave their sounds.
    GENERAL80 = 80,              # Decay Generic or on/off switch ≤63 off, ≥64 on
    USER_DECAYTIME = 80,         # Decay time
    GENERAL81 = 81,              # Hi-Pass Filter Frequency or Generic on/off switch ≤63 off, ≥64 on
    GENERAL82 = 82,              # Generic on/off switch ≤63 off, ≥64 on
    GENERAL83 = 83,              # Generic on/off switch ≤63 off, ≥64 on
    PORTAMENTOCC = 84,           # Controls the amount of Portamento.
    HIGHRESVELOCITYPREFIX = 88,  # Extends the range of possible velocity values
    EFFECTDEPTH1 = 91,           # Usually controls reverb send amount
    USER_REVERB_LEVEL = 91,      # Reverb level
    EFFECTDEPTH2 = 92,           # Usually controls tremolo amount
    USER_TRE_AMP = 92,           #
    EFFECTDEPTH3 = 93,           # Usually controls chorus amount
    EFFECTDEPTH4 = 94,           # Usually controls detune amount
    EFFECTDEPTH5 = 95,           # Usually controls phaser amount
    DATAINCREMENT = 96,          # Usually used to increment data for RPN and NRPN messages.
    DATADECREMENT = 97,          # Usually used to decrement data for RPN and NRPN messages.
    NRPNLSB = 98,                # For controllers 6, 38, 96, and 97, it selects the NRPN parameter.
    NRPNMSB = 99,                # For controllers 6, 38, 96, and 97, it selects the NRPN parameter.
    RPNLSB = 100,                # For controllers 6, 38, 96, and 97, it selects the RPN parameter.
    RPNMSB = 101,                # For controllers 6, 38, 96, and 97, it selects the RPN parameter.
    USER_MTRE_TYPE = 102,		 #
    USER_MTRE_PEAK = 103,		 #
    USER_MTRE_AMP = 104,	     #
    USER_MTRE_FREQ = 105,		 #
    USER_MVIB_TYPE = 106,		 #
    USER_MVIB_PEAK = 107,		 #
    USER_MVIB_AMP = 108,	 	 #
    USER_MVIB_FREQ = 109,		 #
    USER_MWOW_TYPE = 110,		 #
    USER_MWOW_PEAK = 111,		 #
    USER_MWOW_AMP = 112,		 #
    USER_MWOW_FREQ = 113,		 #
    USER_MFILTER_TYPE = 114,	 #
    USER_MFILTER_QFACTOR = 115,	 #
    USER_MFILTER_CUTOFF = 116,	 #
    USER_PRESET = 118,           # Preset
    USER_MODECONTROL = 119,      # 
    ALLSOUNDOFF = 120,           # Mutes all sound. It does so regardless of release time or sustain. (See MIDI CC 123)
    RESETALL = 121,              # It will reset all controllers to their default.
    LOCALSWITCH = 122,           # Turns internal connection of a MIDI keyboard or workstation, etc. on or off. If you use a computer, you will most likely want local control off to avoid notes being played twice. Once locally and twice when the note is sent back from the computer to your keyboard.
    ALLNOTESOFF = 123,           # Mutes all sounding notes. Release time will still be maintained, and notes held by sustain will not turn off until sustain pedal is depressed.
    OMNIMODEOFF = 124,           # Sets to “Omni Off” mode.
    OMNIMODEON = 125,            # Sets to “Omni On” mode.
    MONOMODE = 126,              # Sets device mode to Monophonic. The value equals the number of channels, or 0 if the number of channels equals the number of voices in the receiver.
    POLYMODE = 127               # Sets device mode to Polyphonic.

class NoteNum(IntEnum):
	NN_CM1 = 0,
	NN_CSM1 = 1,
	NN_DM1 = 2,
	NN_DSM1 = 3,
	NN_EM1 = 4,
	NN_FM1 = 5,
	NN_FSM1 = 6,
	NN_GM1 = 7,
	NN_GSM1 = 8,
	NN_AM1 = 9,
	NN_ASM1 = 10,
	NN_BM1 = 11,
	NN_C0 = 12,
	NN_CS0 = 13,
	NN_D0 = 14,
	NN_DS0 = 15,
	NN_E0 = 16,
	NN_F0 = 17,
	NN_FS0 = 18,
	NN_G0 = 19,
	NN_GS0 = 20,
	NN_A0 = 21,
	NN_AS0 = 22,
	NN_B0 = 23,
	NN_C1 = 24,
	NN_CS1 = 25,
	NN_D1 = 26,
	NN_DS1 = 27,
	NN_E1 = 28,
	NN_F1 = 29,
	NN_FS1 = 30,
	NN_G1 = 31,
	NN_GS1 = 32,
	NN_A1 = 33,
	NN_AS1 = 34,
	NN_B1 = 35,
	NN_C2 = 36,
	NN_CS2 = 37,
	NN_D2 = 38,
	NN_DS2 = 39,
	NN_E2 = 40,
	NN_F2 = 41,
	NN_FS2 = 42,
	NN_G2 = 43,
	NN_GS2 = 44,
	NN_A2 = 45,
	NN_AS2 = 46,
	NN_B2 = 47,
	NN_C3 = 48,
	NN_CS3 = 49,
	NN_D3 = 50,
	NN_DS3 = 51,
	NN_E3 = 52,
	NN_F3 = 53,
	NN_FS3 = 54,
	NN_G3 = 55,
	NN_GS3 = 56,
	NN_A3 = 57,
	NN_AS3 = 58,
	NN_B3 = 59,
	NN_C4 = 60,
	NN_CS4 = 61,
	NN_D4 = 62,
	NN_DS4 = 63,
	NN_E4 = 64,
	NN_F4 = 65,
	NN_FS4 = 66,
	NN_G4 = 67,
	NN_GS4 = 68,
	NN_A4 = 69,
	NN_AS4 = 70,
	NN_B4 = 71,
	NN_C5 = 72,
	NN_CS5 = 73,
	NN_D5 = 74,
	NN_DS5 = 75,
	NN_E5 = 76,
	NN_F5 = 77,
	NN_FS5 = 78,
	NN_G5 = 79,
	NN_GS5 = 80,
	NN_A5 = 81,
	NN_AS5 = 82,
	NN_B5 = 83,
	NN_C6 = 84,
	NN_CS6 = 85,
	NN_D6 = 86,
	NN_DS6 = 87,
	NN_E6 = 88,
	NN_F6 = 89,
	NN_FS6 = 90,
	NN_G6 = 91,
	NN_GS6 = 92,
	NN_A6 = 93,
	NN_AS6 = 94,
	NN_B6 = 95,
	NN_C7 = 96,
	NN_CS7 = 97,
	NN_D7 = 98,
	NN_DS7 = 99,
	NN_E7 = 100,
	NN_F7 = 101,
	NN_FS7 = 102,
	NN_G7 = 103,
	NN_GS7 = 104,
	NN_A7 = 105,
	NN_AS7 = 106,
	NN_B7 = 107,
	NN_C8 = 108,
	NN_CS8 = 109,
	NN_D8 = 110,
	NN_DS8 = 111,
	NN_E8 = 112,
	NN_F8 = 113,
	NN_FS8 = 114,
	NN_G8 = 115,
	NN_GS8 = 116,
	NN_A8 = 117,
	NN_AS8 = 118,
	NN_B8 = 119,
	NN_C9 = 120,
	NN_CS9 = 121,
	NN_D9 = 122,
	NN_DS9 = 123,
	NN_E9 = 124,
	NN_F9 = 125,
	NN_FS9 = 126,
